- name: Provision Docker Droplet with Docker Compose
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Install Docker Compose
      pip:
        name: docker-compose
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Clone/Pull repository to APP_PATH
      git:
        repo: "https://github.com/{{ GITHUB_REPOSITORY }}"
        dest: "{{ APP_PATH }}"
        version: "{{ GITHUB_REPOSITORY_BRANCH }}"
        update: yes  # This will pull the latest changes if the repo already exists
        force: no    # Prevents the repo from being overwritten

    - name: Run Docker Compose up
      command: docker-compose -f "{{ DOCKER_COMPOSE_PATH | default(APP_PATH + '/docker-compose.yml') }}" up -d

    - name: Set permissions for www user
      file:
        path: /home/www/app
        owner: www
        group: www
        mode: "u=rwx,g=rx,o=rx"
