- name: Provision Docker Droplet with Docker Compose
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker and dependencies
      apt:
        pkg:
        - ca-certificates 
        - curl 
        - gnupg 
        - lsb-release
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
        state: present

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Check if Git safe directory is already configured
      shell: |
        git config --global --get safe.directory {{ APP_PATH }} || echo "not set"
      register: git_safe_directory
      changed_when: false
    
    - name: Configure Git safe directory if not set
      command: git config --global --add safe.directory {{ APP_PATH }}
      when: git_safe_directory.stdout == "not set"

    # - name: Set permissions for www user
    #   file:
    #     path: "{{ APP_PATH }}"
    #     owner: "{{ APP_USER }}"
    #     group: "{{ APP_USER }}"
    #     mode: "u=rwx,g=rx,o=rx"
  
    - name: Clone/Pull repository to APP_PATH
      git:
        repo: "https://github.com/{{ GITHUB_REPOSITORY }}"
        dest: "{{ APP_PATH }}"
        version: "{{ GITHUB_REPOSITORY_BRANCH | default('main') }}"
        update: yes
        force: no

    - name: Run Docker Compose up
      command: docker compose -f "{{ DOCKER_COMPOSE_PATH | default(APP_PATH + '/docker-compose.yml') }}" up -d

