- name: Provision Docker Droplet
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install Docker SDK for Python
      pip:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create Docker container
      docker_container:
        name: app_container
        image: node:14
        state: started
        ports:
          - "80:80"
        volumes:
          - /home/www/app:/usr/src/app

    - name: Set permissions for www user
      file:
        path: /home/www/app
        owner: www
        group: www
        mode: "u=rwx,g=rx,o=rx"
